//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANZHFR.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public short Content_ID { get; set; }
        public string Content_Key { get; set; }
        public string Content_HTML { get; set; }
        public string Content_Text { get; set; }
    }
}
