//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANZHFR.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exporting
    {
        public string HospitalName { get; set; }
        public Nullable<long> HospitalID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string MRN { get; set; }
        public string Phone { get; set; }
        public System.DateTime DOB { get; set; }
        public string Sex { get; set; }
        public string Indig { get; set; }
        public string Ethnic { get; set; }
        public string PostCode { get; set; }
        public string Medicare { get; set; }
        public string PatientType { get; set; }
        public string AdmissionViaED { get; set; }
        public string UsualResidence { get; set; }
        public string TransferHospital { get; set; }
        public System.DateTime TransferDateTime { get; set; }
        public System.DateTime ArrivalDateTime { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public System.DateTime InHospFractureDateTime { get; set; }
        public string WardType { get; set; }
        public string PreAdWalk { get; set; }
        public string AMTS { get; set; }
        public string ASAGrade { get; set; }
        public string CognitiveAssessment { get; set; }
        public string CognitiveState { get; set; }
        public string BoneMed { get; set; }
        public string PreOpMedAss { get; set; }
        public string FractureSide { get; set; }
        public string AtypicalFracture { get; set; }
        public string FractureType { get; set; }
        public string Surgery { get; set; }
        public System.DateTime SurgeryDateTime { get; set; }
        public string SurgeryDelay { get; set; }
        public string SurgeryDelayOther { get; set; }
        public string Anaesthesia { get; set; }
        public string Analgesia { get; set; }
        public string ConsultantPresent { get; set; }
        public string Operation { get; set; }
        public string InterOpFracture { get; set; }
        public string FullWeightBear { get; set; }
        public string Mobilisation { get; set; }
        public string FirstDayWalking { get; set; }
        public string PressureUlcers { get; set; }
        public string GeriatricAssessment { get; set; }
        public System.DateTime GeriatricAssDateTime { get; set; }
        public string FallsAssessment { get; set; }
        public string BoneMedDischarge { get; set; }
        public System.DateTime WardDischargeDate { get; set; }
        public string DischargeDest { get; set; }
        public System.DateTime HospitalDischargeDate { get; set; }
        public string DischargeResidence { get; set; }
        public System.DateTime FollowupDate30 { get; set; }
        public System.DateTime HealthServiceDischarge30 { get; set; }
        public string Survival30 { get; set; }
        public string UResidence { get; set; }
        public string Residence30 { get; set; }
        public string WeightBear30 { get; set; }
        public string WalkingAbility30 { get; set; }
        public string BoneMed30 { get; set; }
        public string Reoperation30 { get; set; }
        public System.DateTime FollowupDate120 { get; set; }
        public System.DateTime HealthServiceDischarge120 { get; set; }
        public string Survival120 { get; set; }
        public string Residence120 { get; set; }
        public string WeightBear120 { get; set; }
        public string WalkingAbility120 { get; set; }
        public string BoneMed120 { get; set; }
        public string Reoperation120 { get; set; }
        public string DeleriumAssessment { get; set; }
        public System.DateTime DeathDate { get; set; }
        public Nullable<bool> Informed { get; set; }
        public Nullable<bool> CannotFollowup { get; set; }
        public Nullable<bool> OptedOut { get; set; }
        public string PainAssessment { get; set; }
        public string PainManagement { get; set; }
        public string Malnutrition { get; set; }
        public System.DateTime StartDate { get; set; }
    }
}
