//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANZHFR.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalStatus
    {
        public HospitalStatus()
        {
            this.Hospitals = new HashSet<Hospital>();
        }
    
        public short HospitalStatusID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Hospital> Hospitals { get; set; }
    }
}
