//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANZHFR.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualityPatient
    {
        public int QualityID { get; set; }
        public int ANZHFRID { get; set; }
        public long HospitalID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string MRN { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> QDOB { get; set; }
        public string Sex { get; set; }
        public Nullable<int> QSex { get; set; }
        public string Indig { get; set; }
        public Nullable<int> QIndig { get; set; }
        public string Ethnic { get; set; }
        public Nullable<int> QEthnic { get; set; }
        public string PostCode { get; set; }
        public string Medicare { get; set; }
        public string PatientType { get; set; }
        public Nullable<int> QPatientType { get; set; }
        public string AdmissionViaED { get; set; }
        public Nullable<int> QAdmissionViaED { get; set; }
        public string UResidence { get; set; }
        public Nullable<int> QUResidence { get; set; }
        public string TransferHospital { get; set; }
        public Nullable<int> QTransferHospital { get; set; }
        public Nullable<System.DateTime> TransferDateTime { get; set; }
        public Nullable<int> QTransferDateTime { get; set; }
        public Nullable<int> Q15TransferDateTime { get; set; }
        public Nullable<System.DateTime> ArrivalDateTime { get; set; }
        public Nullable<int> QArrivalDateTime { get; set; }
        public Nullable<int> Q15ArrivalDateTime { get; set; }
        public Nullable<System.DateTime> DepartureDateTime { get; set; }
        public Nullable<int> QDepartureDateTime { get; set; }
        public Nullable<int> Q15DepartureDateTime { get; set; }
        public Nullable<System.DateTime> InHospFractureDateTime { get; set; }
        public Nullable<int> QInHospFractureDateTime { get; set; }
        public Nullable<int> Q15InHospFractureDateTime { get; set; }
        public string WardType { get; set; }
        public Nullable<int> QWardType { get; set; }
        public string PreAdWalk { get; set; }
        public Nullable<int> QPreAdWalk { get; set; }
        public string AMTS { get; set; }
        public Nullable<int> QAMTS { get; set; }
        public string ASAGrade { get; set; }
        public Nullable<int> QASAGrade { get; set; }
        public string CognitiveState { get; set; }
        public Nullable<int> QCognitiveState { get; set; }
        public string BoneMed { get; set; }
        public Nullable<int> QBoneMed { get; set; }
        public string PreOpMedAss { get; set; }
        public Nullable<int> QPreOpMedAss { get; set; }
        public string FractureSide { get; set; }
        public string AtypicalFracture { get; set; }
        public Nullable<int> QAtypicalFracture { get; set; }
        public string FractureType { get; set; }
        public Nullable<int> QFractureType { get; set; }
        public string Surgery { get; set; }
        public Nullable<int> QSurgery { get; set; }
        public Nullable<System.DateTime> SurgeryDateTime { get; set; }
        public Nullable<int> QSurgeryDateTime { get; set; }
        public Nullable<int> Q15SurgeryDateTime { get; set; }
        public string SurgeryDelay { get; set; }
        public Nullable<int> QSurgeryDelay { get; set; }
        public string SurgeryDelayOther { get; set; }
        public string Anaesthesia { get; set; }
        public Nullable<int> QAnaesthesia { get; set; }
        public string Analgesia { get; set; }
        public Nullable<int> QAnalgesia { get; set; }
        public string ConsultantPresent { get; set; }
        public Nullable<int> QConsultantPresent { get; set; }
        public string Operation { get; set; }
        public Nullable<int> QOperation { get; set; }
        public string InterOpFracture { get; set; }
        public Nullable<int> QInterOpFracture { get; set; }
        public string FullWeightBear { get; set; }
        public Nullable<int> QFullWeightBear { get; set; }
        public string Mobilisation { get; set; }
        public Nullable<int> QMobilisation { get; set; }
        public string PressureUlcers { get; set; }
        public Nullable<int> QPressureUlcers { get; set; }
        public string GeriatricAssessment { get; set; }
        public Nullable<int> QGeriatricAssessment { get; set; }
        public Nullable<System.DateTime> GeriatricAssDateTime { get; set; }
        public Nullable<int> QGeriatricAssDateTime { get; set; }
        public string FallsAssessment { get; set; }
        public Nullable<int> QFallsAssessment { get; set; }
        public string BoneMedDischarge { get; set; }
        public Nullable<int> QBoneMedDischarge { get; set; }
        public Nullable<System.DateTime> WardDischargeDate { get; set; }
        public Nullable<int> QWardDischargeDate { get; set; }
        public string DischargeDest { get; set; }
        public Nullable<int> QDischargeDest { get; set; }
        public Nullable<System.DateTime> HospitalDischargeDate { get; set; }
        public Nullable<int> QHospitalDischargeDate { get; set; }
        public Nullable<short> OLengthofStay { get; set; }
        public Nullable<short> HLengthofStay { get; set; }
        public string DischargeResidence { get; set; }
        public Nullable<int> QDischargeResidence { get; set; }
        public Nullable<decimal> Completeness { get; set; }
        public string CompleteExemption { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ModifiedBy { get; set; }
        public string CognitiveAssessment { get; set; }
        public Nullable<int> QCognitiveAssessment { get; set; }
        public string PainAssessment { get; set; }
        public Nullable<int> QPainAssessment { get; set; }
        public string PainManagement { get; set; }
        public Nullable<int> QPainManagement { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> Informed { get; set; }
        public Nullable<bool> OptedOut { get; set; }
        public Nullable<bool> CannotFollowup { get; set; }
        public string DeleriumAssessment { get; set; }
        public Nullable<int> QDeleriumAssessment { get; set; }
        public string Malnutrition { get; set; }
        public Nullable<int> QMalnutrition { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public Nullable<int> QDeathDate { get; set; }
        public string FirstDayWalking { get; set; }
        public Nullable<int> QFirstDayWalking { get; set; }
        public Nullable<int> QualityScore { get; set; }
        public Nullable<int> QualityScore30 { get; set; }
        public Nullable<int> QualityScoreMM { get; set; }
        public string QualityScoreComments { get; set; }
    }
}
