//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANZHFR.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public string Code { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string XLabel { get; set; }
        public string YLabel { get; set; }
        public string Description { get; set; }
        public string StoredProcName { get; set; }
        public bool ActiveFlag { get; set; }
    }
}
