//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANZHFR.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int SurveyID { get; set; }
        public long HospitalID { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<bool> SubmittedFlag { get; set; }
        public Nullable<int> EstimatedRecordsPerMonth { get; set; }
        public string RoleName { get; set; }
        public string EstimatedRecords { get; set; }
        public string DesignatedMajorTraumaCentre { get; set; }
        public string FormalOrthogeriatricService { get; set; }
        public string ModelOfCare { get; set; }
        public string ModelCareOther { get; set; }
        public string ProtocolAccessCTMRI { get; set; }
        public string HipFracturePathway { get; set; }
        public string VTEProtocol { get; set; }
        public string ProtocolPain { get; set; }
        public string PlannedList { get; set; }
        public string ChoiceOfAnaesthesia { get; set; }
        public string LocalNerveBlocks { get; set; }
        public string LocalNerveBlocksPostoperative { get; set; }
        public string WeekendTherapyServices { get; set; }
        public string WrittenCareInformation { get; set; }
        public string InPatientRehabilitation { get; set; }
        public string SupportedHomeBasedRehabilitation { get; set; }
        public string IndividualisedWrittenInformation { get; set; }
        public string FallsClinicPublic { get; set; }
        public string OsteoporosisClinicPublic { get; set; }
        public string CombinedFallsBoneHealthClinicPublic { get; set; }
        public string OrthopaedicClinicPublic { get; set; }
        public string FractureLiaisonService { get; set; }
        public string CollectLocalHipFractureData { get; set; }
        public string WhoCollectsData { get; set; }
        public string ServiceChanges { get; set; }
        public string ServiceChangesPlanned { get; set; }
        public string IdentifiedBarriers { get; set; }
        public string IdentifiedBarrierDetails { get; set; }
        public Nullable<long> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Hospital Hospital { get; set; }
        public virtual User User { get; set; }
    }
}
