//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANZHFR.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SynonymChild
    {
        public long Id { get; set; }
        public long SynonymID { get; set; }
        public string Word { get; set; }
    
        public virtual Synonym Synonym { get; set; }
    }
}
