//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ANZHFR.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearlyValidation
    {
        public long HospitalID { get; set; }
        public int ANZHFRID { get; set; }
        public string Name { get; set; }
        public string Medicare { get; set; }
        public string MRN { get; set; }
        public string FractureSide { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<int> AgeAtAdmission { get; set; }
        public Nullable<int> TimeInED { get; set; }
        public Nullable<int> TimeToSurgery { get; set; }
        public Nullable<int> LengthOfAcuteStay { get; set; }
        public Nullable<int> LengthOfStay { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
